version: '3'
services:
  master:
    build: ./master
    ports:
      - 8080:8080
    volumes:
      - ./master/:/work
      - ./front/dist:/work/public
    command: ['python', 'app.py']
    links:
      - rasp1
      - rasp2
      - room
      - sensor

  rasp1:
    build: ./rasp
    volumes:
      - ./rasp/:/work
    command: ['python', 'app.py']

  rasp2:
    build: ./rasp
    volumes:
      - ./rasp:/work
    command: ['python', 'app.py']

  room:
    build: ./room
    volumes:
      - ./room/:/work
    command: ['python', '-m', 'app']
    links:
      - db

  sensor:
    build: ./sensor
    links:
      - db
    volumes:
      - ./sensor/:/work
    command: ['python', 'app.py']

  db:
    build: ./db
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
